<?php
$orderData = $block->getOrderDetails($block->getOrderId());
$giftWrapInfo = unserialize($orderData['gift_wrap_info']);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
$giftWrapModel = $objectManager->get('Excellence\Giftwrap\Model\Giftwrap');
?>
<div class="table-wrapper order-items">
    <?php
        if(!is_array($giftWrapInfo)){
            echo __('No Gift Wrap Found for The Order');
        } else{
    ?>
        <table class="data table table-order-items" id="my-orders-table" summary="<?php /* @escapeNotVerified */ echo $block->getPageTitle() ?>">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo $block->getPageTitle() ?></caption>
            <thead>
                <tr>
                    <th class="col product_name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th class="col product_sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                    <th class="col box"><?php /* @escapeNotVerified */ echo __('Gift Box') ?></th>
                    <th class="col message"><?php /* @escapeNotVerified */ echo __('Gift Message') ?></th>
                    <th class="col gift_price"><?php /* @escapeNotVerified */ echo __('Wrapper Price') ?></th>
                </tr>
            </thead>
        <?php
            foreach ($giftWrapInfo['data'] as $giftWrap) {
                if (!($giftWrap['is_giftwrap'])) {
                    continue;
                }
                $giftWrapData = array();
                if($giftWrap['giftwrap_id'] == 0){
                    $giftWrapData['title'] = $storeConfig->getValue('giftwrap/default_gift_wrap/label', $storeScope);
                    $giftWrapData['image'] = 'default_gift_wrap/'.$storeConfig->getValue('giftwrap/default_gift_wrap/upload_image_id', $storeScope);
                } else{
                    $giftWrapData = $giftWrapModel->load($giftWrap['giftwrap_id'])->getData();
                }
                $productData = $block->getProductBySku($giftWrap['sku']);
                ?>
                <tbody>
                    <tr>
                        <td class="col"><?php echo $productData->getName(); ?></td>
                        <td class="col"><?php echo $productData->getSku(); ?></td>
                        <td class="col"><img src="<?php echo $block->getGiftBoxImageUrl($giftWrapData['image']); ?>" title="<?php echo $giftWrapData['title'] ?>" height='75px' width=75px; /></td>
                        <td class="col"><?php if(empty(trim($giftWrap['message']))){echo '----';} else{ echo $giftWrap['message']; } ?></td>
                        <td class="col"><?php echo $block->getFomattedPrice($giftWrap['giftwrap_price']); ?></td>
                    </tr>
                </tbody>
                <?php
            }
        ?>
            <tfoot>
                <tr class="price-type">
                    <th class="mark" colspan="4">
                        <?php echo __('Price applied on'); ?>
                    </th>
                    <td class="amount">
                        <span class="price">
                            <?php
                            if($giftWrapInfo['total']['per_order']){
                                echo __('Order');
                            } else{
                                echo __('Items');
                            }
                            ?>
                        </span>
                    </td>
                </tr>
                <tr class="grand_total">
                    <th class="mark" colspan="4">
                        <strong>
                            <?php echo __('Total'); ?>
                        </strong>
                    </th>
                    <td class="amount">
                        <strong>
                            <span class="price">
                                <?php echo $block->getFomattedPrice($giftWrapInfo['total']['price']); ?>
                            </span>
                        </strong>
                    </td>
                </tr>
            </tfoot>
        </table>
        <?php } ?>
</div>