<?php
$orderData = $block->getOrderDetails($block->getOrderId());
$giftWrapInfo = unserialize($orderData['gift_wrap_info']);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
$giftWrapModel = $objectManager->get('Excellence\Giftwrap\Model\Giftwrap');
?>
<caption class="table-caption"><?php /* @escapeNotVerified */ echo $block->getPageTitle() ?></caption>
<thead>
    <tr>
        <th class="col product_name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
        <th class="col product_sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
        <th class="col box"><?php /* @escapeNotVerified */ echo __('Gift Box') ?></th>
        <th class="col message"><?php /* @escapeNotVerified */ echo __('Gift Message') ?></th>
        <th class="col gift_price"><?php /* @escapeNotVerified */ echo __('Wrapper Price') ?></th>
    </tr>
</thead>
<?php
    foreach ($giftWrapInfo['data'] as $giftWrap) {
        if (!($giftWrap['is_giftwrap'])) {
            continue;
        }
        $giftWrapData = array();
        if($giftWrap['giftwrap_id'] == 0){
            $giftWrapData['title'] = $storeConfig->getValue('giftwrap/default_gift_wrap/label', $storeScope);
            $giftWrapData['image'] = 'default_gift_wrap/'.$storeConfig->getValue('giftwrap/default_gift_wrap/upload_image_id', $storeScope);
        } else{
            $giftWrapData = $giftWrapModel->load($giftWrap['giftwrap_id'])->getData();
        }
        $productData = $block->getProductBySku($giftWrap['sku']);
        ?>
        <tbody>
            <tr>
                <td class="col"><?php echo $productData->getName(); ?></td>
                <td class="col"><?php echo $productData->getSku(); ?></td>
                <td class="col"><img src="<?php echo $block->getGiftBoxImageUrl($giftWrapData['image']); ?>" title="<?php echo $giftWrapData['title'] ?>" height='75px' width=75px; /></td>
                <td class="col"><?php if(empty(trim($giftWrap['message']))){echo '----';} else{ echo $giftWrap['message']; } ?></td>
                <td class="col"><?php echo $block->getFomattedPrice($giftWrap['giftwrap_price']); ?></td>
            </tr>
        </tbody>
        <?php
    }
?>