<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block
 */
$_order = $block->getOrder() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <?php $i = 0;
                $columns = $block->getColumns();
                $lastItemNumber = count($columns) ?>
                <?php foreach ($columns as $columnName => $columnTitle):?>
                    <?php $i++; ?>
                    <th class="col-<?php /* @noEscape */ echo $columnName ?><?php /* @noEscape */ echo ($i === $lastItemNumber ? ' last' : '')?>"><span><?php /* @noEscape */ echo $columnTitle ?></span></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            }?>
            <tbody class="<?php /* @noEscape */ echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>

<!-- Gift Wrap Info -->
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productModel = $objectManager->get('Magento\Catalog\Model\Product');
    $giftWrapModel = $objectManager->get('Excellence\Giftwrap\Model\Giftwrap');
    $mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $storeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
    $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
    $giftWrapInfo = unserialize($_order->getData('gift_wrap_info'));
    if(is_array($giftWrapInfo)){
?>
        <div class="admin__page-section-title">
            <span class="title">Gift Wrap Details</span>
        </div>
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary edit-order-table">
                <thead>
                    <tr class="headings">
                        <th class="col"><?php echo __('Product'); ?></th>
                        <th class="col"><?php echo __('Gift Box'); ?></th>
                        <th class="col"><?php echo __('Gift Message'); ?></th>
                        <th class="col"><?php echo __('Wrapper Price'); ?></th>
                    </tr>
                </thead>
                <?php
                    foreach ($giftWrapInfo['data'] as $giftWrap) {
                        if (!($giftWrap['is_giftwrap'])) {
                            continue;
                        }
                        $giftWrapData = array();
                        if($giftWrap['giftwrap_id'] == 0){
                            $giftWrapData['title'] = $storeConfig->getValue('giftwrap/default_gift_wrap/label', $storeScope);
                            $giftWrapData['image'] = 'default_gift_wrap/'.$storeConfig->getValue('giftwrap/default_gift_wrap/upload_image_id', $storeScope);
                        } else{
                            $giftWrapData = $giftWrapModel->load($giftWrap['giftwrap_id'])->getData();
                        }
                        $productData = $productModel->load($productModel->getIdBySku($giftWrap['sku']));
                        ?>
                        <tbody>
                            <tr>
                                <td class="col">
                                    <div class="product-title"><?php echo $productData->getName(); ?></div>
                                    <div class="product-sku-block"><span><?php echo __('SKU').": ". $productData->getSku(); ?></span></div>
                                </td>
                                <td class="col"><img src="<?php echo $mediaUrl.$giftWrapData['image']; ?>" title="<?php echo $giftWrapData['title'] ?>" height='75px' width=75px; /></td>
                                <td class="col"><?php if(empty(trim($giftWrap['message']))){echo '----';} else{ echo $giftWrap['message']; } ?></td>
                                <td class="col"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($giftWrap['giftwrap_price'], true, false); ?></td>
                            </tr>
                        </tbody>
                        <?php
                    }
                ?>
            </table>
        </div>
<?php
    }
?>
